### ISSUE TITLE
问一下关于实现方式

### ISSUE THREAD

**Issue by jerryskyr** [smallbeanteng/dubbo-gateway#1]
由于代码太多了, 还没仔细看
想问一下, 关于实现是采用什么方式实现的动态调用呢?
可否对一些关键实现类描述一下?
如果后端服务新增接口的话, 网关是否需要重新打包部署呢? 
因为我看到zuul模块也是引入了api接口包的, 猜测后端新增接口, 网关应该是需要重新编译和部署的, 对吧?

**Comment by smallbeanteng** [comment]
由于平时太忙了，这个项目又是个人在维护，所以少了些描述，后续会逐渐补齐注释及描述，简单讲一下吧，这个项目目的是提供一个适用于spring mvc,zull,spring gateway 等网关的公共dubbo协议转换层，目前已经整合了spring mvc,zull1 【比较完善】spring gateway【还未整合安全方案】,主要实现其实是三层
安全层：(默认采用的是spring security 不引用spring security cas则不会生效),
协议转换层：主要三个步骤
第一步：过滤器拦截请求【不管是网关还是spring mvc都有过滤器】，根据@PathMapping设置的path匹配是否需要协议转换
第二步：请求数据转换为接口参数
第三步：调用dubbo代理，过滤器都在dubbo-gateway-core/src/main/java/com/atommiddleware/cloud/core/filter 里面
代理层：主要是根据接口生成了dubbo 接口调用的代理，默认实现在dubbo-gateway-core/src/main/java/com/atommiddleware/cloud/core/annotation/DefaultDubboApiWrapperFactory.java

当然生成的代理是使用
@DubboReference
 private 接口名称  变量
类似这样的非泛化方式调用所以如果你的接口变动了，就需要重新打包部署
